// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiBnN8MbkZdqHV747IudAss9hmqKrZRw',
    appId: '1:360836707878:web:ae8331d51b565336ccd8e7',
    messagingSenderId: '360836707878',
    projectId: 'hackpr-28268',
    authDomain: 'hackpr-28268.firebaseapp.com',
    storageBucket: 'hackpr-28268.appspot.com',
    measurementId: 'G-FS6SGYHS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgHaC7UopGJqNpRA3p9-_Rb5zZVc1RiEU',
    appId: '1:360836707878:android:0a2d1d67d5291619ccd8e7',
    messagingSenderId: '360836707878',
    projectId: 'hackpr-28268',
    storageBucket: 'hackpr-28268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZopp1lqKZzPfoiQhF5dl8n-8hXAgR294',
    appId: '1:360836707878:ios:157e7c325f5a5493ccd8e7',
    messagingSenderId: '360836707878',
    projectId: 'hackpr-28268',
    storageBucket: 'hackpr-28268.appspot.com',
    iosBundleId: 'com.example.appecomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZopp1lqKZzPfoiQhF5dl8n-8hXAgR294',
    appId: '1:360836707878:ios:ee9558269bd38395ccd8e7',
    messagingSenderId: '360836707878',
    projectId: 'hackpr-28268',
    storageBucket: 'hackpr-28268.appspot.com',
    iosBundleId: 'com.example.appecomm.RunnerTests',
  );
}
